function solve() {
    let stops = ['depot']; // initialize array to hold first stop hold additional stops as generated by API call
    let i = 0; // declare i variable to dynamically change var url for API calls 
    function depart() {
        let url = `https://judgetests.firebaseio.com/schedule/${stops[i]}.json`; // declare url var for request as string literal with stopId var being passed in

        fetch(url).then(function(response){ // impliment the fetch method to make out GET request 
            let infoclass = document.getElementsByClassName('info')[0]; // declare infoclass var to select the class of the output span
            
            if (response.ok) { // write "if" conditional to make sure our API call is ok
                response.json().then(function(buses){ // if response is ok, then create a nameless function an pass in the response data in a new param called busses 
                    document.getElementById('depart').disabled = true; // set clicked button with id of 'depart' to disabled = true, per instruction request
                    document.getElementById('arrive').disabled = false; // set clicked button with id of 'arive' to disabled = false, per instruction request
                    // console.log(buses);
                    infoclass.textContent = `Next stop ${buses.name}`; // set the textContent of var infoclass = response passed in by buses.name
                    stops.push(buses.next); // push the buses.next value into the stops array
                    // console.log(stops);
                    i++; // increment the i var 
                    // console.log(i);
                });
            } else { // if fetch GET response is not ok
                document.getElementById('depart').disabled = true; // disable the depart button, per instruction requst 
                document.getElementById('arrive').disabled = true; // disable the arrive button, per instruction requst 
                infoclass.textContent = 'Error'; // change the textContent span value in var infoclass to "Error"
                throw err; // throw the error 
            }
        });
    }

    function arrive() {
        let url = `https://judgetests.firebaseio.com/schedule/${stops[i]}.json`; // declare url var for request as string literal with stopId var being passed in

        fetch(url).then(function (response) { // impliment the fetch method to make out GET request 
            let infoclass = document.getElementsByClassName('info')[0]; // declare infoclass var to select the class of the output span

            if (response.ok) { // write "if" conditional to make sure our API call is ok
                response.json().then(function (buses) { // if response is ok, then create a nameless function an pass in the response data in a new param called busses 
                    document.getElementById('arrive').disabled = true; // set clicked button with id of 'arrive' to disabled = true, per instruction request
                    document.getElementById('depart').disabled = false; // set clicked button with id of 'depart' to disabled = true, per instruction request
                    // console.log(buses);
                    infoclass.textContent = `Next stop ${buses.name}`; // set the textContent of var infoclass = response passed in by buses.name
                    stops.push(buses.next); // push the buses.next value into the stops array
                    // console.log(stops);
                    i++; // increment the i var 
                    // console.log(i);
                });
            }
        });
    }

    return { // return Object with functions
        depart, // function depart
        arrive // function arrive 
    };
}

let result = solve(); // declare var result to equal function solve